version: "3.7"
services:
  db:
    environment:
      MYSQL_DATABASE: example
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db-password
    image: mariadb:10.6.4-focal
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - spring-mysql
  backend:
    image: 54.91.199.29:8082/backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
      #target: development
    environment:
      MYSQL_HOST: db
    networks:
      - react-spring
      - spring-mysql
    depends_on:
      - db
    restart: on-failure:5
  frontend:
    image: 54.91.199.29:8082/frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
      #target: development
    ports:
      - 3000:3000
    networks:
      - react-spring
    depends_on:
      - backend
volumes:
  db-data: {}
secrets:
  db-password:
    file: db/password.txt
networks:
  react-spring: {}
  spring-mysql: {}
