name: Docker Image CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
jobs:
  #build_and_test
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Enable experimental features for the Docker daemon and CLI
        run: |
          echo $'{\n  "insecure-registries": ["54.91.199.29:8082"]\n}' | sudo tee /etc/docker/daemon.json
          sudo service docker restart
    - name: up the compose
      run: |
        docker compose up -d
        docker compose push
    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: |
         .
         !./.git
         !./.github
  #upload_artifact
  # upload_artifact:
  #   needs: upload_to_nexus
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v3
  #   - name: Create the Artifact
  #     uses: actions/upload-artifact@v3
  #     with:
  #       name: my-artifact--${{ github.sha }}
  #       path: |
  #         .
  #         !./.git
  #         !./.github
  #   - name: echo registry
  #     run: echo "${{ vars.REGISTRY_HOST }}"
    # - name: Set env as secret
    #   env:
    #     MY_VAL: ${{ secrets.TEST_SECRET }}
    #   run: |
    #     import os
    #     for q in (os.getenv("MY_VAL")):
    #       print(q)
    #   shell: python
      
