name: Docker Image CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build the compose
      run: docker compose build

  test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: up the compose
      run: docker compose up -d
  upload_to_nexus:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: show images
      run: docker compose images
    # - name: Set env as secret
    #   env:
    #     MY_VAL: ${{ secrets.TEST_SECRET }}
    #   run: |
    #     import os
    #     for q in (os.getenv("MY_VAL")):
    #       print(q)
    #   shell: python
      
