name: Docker Image CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: docker compose test
      uses: adambirds/docker-compose-action@v1.3.0
      with:
        compose-file: "./docker-compose.yaml"
        #down-flags: "--volumes"
        services: |
          db
          backend
          frontend
        test-container: frontend
        test-command: "npm test"
    #- name: Build the stack
     # run: docker compose build
    - name: Set env as secret
      env:
        MY_VAL: ${{ secrets.TEST_SECRET }}
      run: |
        import os
        for q in (os.getenv("MY_VAL")):
          print(q)
      shell: python
