name: Docker Image CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build the stack
      run: docker compose build
    - name: Set up secret file
      env:
        DEBUG_PASSWORD: ${{ secrets.TEST_SECRET }}
      run: |
        echo $DEBUG_PASSWORD >> secrets.txt

    - name: Run tmate
      uses: mxschmitt/action-tmate@v2
