name: Docker Image CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
jobs:

  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: up the compose
      run: docker compose up -d
    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: |
         .
         !./.git
         !./.github
  upload_to_nexus:
    needs: build_and_test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: push the compose
      run: docker compose push
  upload_artifact:
    needs: upload_to_nexus
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Create the Artifact
      uses: actions/upload-artifact@v3
      with:
        name: my-artifact--${{ github.sha }}
        path: |
          .
          !./.git
          !./.github
    - name: echo registry
      run: echo "${{ vars.REGISTRY_HOST }}"
    # - name: Set env as secret
    #   env:
    #     MY_VAL: ${{ secrets.TEST_SECRET }}
    #   run: |
    #     import os
    #     for q in (os.getenv("MY_VAL")):
    #       print(q)
    #   shell: python
      
