name: Project 6 Build and Push

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
jobs:
  #build_and_test
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Dotenv Action
      id: dotenv
      uses: falti/dotenv-action@v1.0.4
    - name: Set current date as env variable
      run: echo "NOW=$(date +'%Y_%m_%d_%H_%M_%S')" >> $GITHUB_ENV
    - name: Enable experimental features for the Docker daemon and CLI
      run: |
        echo $'{\n  "insecure-registries": ["${{ steps.dotenv.outputs.nexus_server }}:8082"]\n}' | sudo tee /etc/docker/daemon.json
        sudo service docker restart
    - uses: docker/login-action@v2
      with:
        registry: ${{ steps.dotenv.outputs.nexus_server }}:8082
        username: ${{ secrets.NEXUS_USER }}
        password: ${{ secrets.NEXUS_PASS }}
    - name: up the compose
      run: |
        docker compose up -d
        docker compose push
    - name: npm publish --scope=@diamant
      run: |
        cd frontend
        npm publish
      env:
        NPM_CONFIG_TOKEN: YWRtaW46Xjd5dXl1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: '11'
    - name: Build with Maven
      run: mvn package --file backend/pom.xml -DoutputDirectory=backend/target
    - name: Nexus Repo Publish
      uses: sonatype-nexus-community/nexus-repo-github-action@master
      with:
        serverUrl: http://${{ steps.dotenv.outputs.nexus_server }}:8081
        username: admin
        password: ${{ secrets.NEXUS_PASS }}
        format: maven2
        repository: reactmysql-maven-h
        coordinates: groupId=com.company artifactId=project version=0.0.1-SNAPSHOT_${{ env.NOW }}
        assets: extension=jar
        filename: backend/target/project-0.0.1-SNAPSHOT.jar
    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: |
         .
         !./.git
         !./.github
  #upload_artifact
  # upload_artifact:
  #   needs: upload_to_nexus
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v3
  #   - name: Create the Artifact
  #     uses: actions/upload-artifact@v3
  #     with:
  #       name: my-artifact--${{ github.sha }}
  #       path: |
  #         .
  #         !./.git
  #         !./.github
  #   - name: echo registry
  #     run: echo "${{ vars.REGISTRY_HOST }}"
    # - name: Set env as secret
    #   env:
    #     MY_VAL: ${{ secrets.TEST_SECRET }}
    #   run: |
    #     import os
    #     for q in (os.getenv("MY_VAL")):
    #       print(q)
    #   shell: python
      
